version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: sylius-labs/coding-standard
    versions:
    - 4.0.2
  - dependency-name: symfony/intl
    versions:
    - 5.2.3
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
  - dependency-name: phpstan/phpstan-shim
    versions:
    - 0.12.0
  - dependency-name: lchrusciel/api-test-case
    versions:
    - 5.0.0
